service: log-slog

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  stage: tech-review
  region: sa-east-1
  memorySize: 128
  timeout: 3
  logRetentionInDays: 1

package:
  individually: true
  patterns:
    - "!./**"
    - ./bin/**

functions:
  main:
    handler: bootstrap
    package:
      artifact: bin/main.zip
    events:
      - http:
          path: /
          method: GET
          cors: true
