service: penguin-store

custom:
  ENVIRONMENT:
    poc: development
    dev: development
    prd: production

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  stage: poc
  region: sa-east-1
  memorySize: 128
  timeout: 3
  logRetentionInDays: 1

  environment:
    ENVIRONMENT: ${self:custom.ENVIRONMENT.${self:provider.stage}}

package:
  individually: true
  patterns:
    - "!./**"
    - ./bin/**

functions:
  bad-handler:
    handler: bootstrap
    package:
      artifact: bin/bad-handler.zip
    events:
      - http:
          path: /bad
          method: GET
          cors: true

  nice-handler:
    handler: bootstrap
    package:
      artifact: bin/nice-handler.zip
    events:
      - http:
          path: /nice
          method: GET
          cors: true
